/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as AceitarConviteRouteImport } from './routes/aceitar-convite'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellAlocacoesRouteImport } from './routes/_shell/alocacoes'
import { Route as ShellCompromissoRouteImport } from './routes/_shell/compromisso'
import { Route as ShellCycleTimeRouteImport } from './routes/_shell/cycle-time'
import { Route as ShellRetrospectivasRouteImport } from './routes/_shell/retrospectivas'
import { Route as EmbedAlocacoesRouteImport } from './routes/embed.alocacoes'
import { Route as ApiPublicEnvprobeRouteImport } from './routes/api/public/envprobe'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AceitarConviteRoute = AceitarConviteRouteImport.update({
  id: '/aceitar-convite',
  path: '/aceitar-convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAlocacoesRoute = ShellAlocacoesRouteImport.update({
  id: '/alocacoes',
  path: '/alocacoes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCompromissoRoute = ShellCompromissoRouteImport.update({
  id: '/compromisso',
  path: '/compromisso',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCycleTimeRoute = ShellCycleTimeRouteImport.update({
  id: '/cycle-time',
  path: '/cycle-time',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRetrospectivasRoute = ShellRetrospectivasRouteImport.update({
  id: '/retrospectivas',
  path: '/retrospectivas',
  getParentRoute: () => ShellRoute,
} as any)
const EmbedAlocacoesRoute = EmbedAlocacoesRouteImport.update({
  id: '/embed/alocacoes',
  path: '/embed/alocacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEnvprobeRoute = ApiPublicEnvprobeRouteImport.update({
  id: '/api/public/envprobe',
  path: '/api/public/envprobe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/admin': typeof AdminRoute
  '/alocacoes': typeof ShellAlocacoesRoute
  '/compromisso': typeof ShellCompromissoRoute
  '/cycle-time': typeof ShellCycleTimeRoute
  '/retrospectivas': typeof ShellRetrospectivasRoute
  '/embed/alocacoes': typeof EmbedAlocacoesRoute
  '/api/public/envprobe': typeof ApiPublicEnvprobeRoute
}
export interface FileRoutesByTo {
  '/aceitar-convite': typeof AceitarConviteRoute
  '/admin': typeof AdminRoute
  '/alocacoes': typeof ShellAlocacoesRoute
  '/compromisso': typeof ShellCompromissoRoute
  '/cycle-time': typeof ShellCycleTimeRoute
  '/retrospectivas': typeof ShellRetrospectivasRoute
  '/embed/alocacoes': typeof EmbedAlocacoesRoute
  '/': typeof ShellIndexRoute
  '/api/public/envprobe': typeof ApiPublicEnvprobeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/aceitar-convite': typeof AceitarConviteRoute
  '/admin': typeof AdminRoute
  '/_shell/alocacoes': typeof ShellAlocacoesRoute
  '/_shell/compromisso': typeof ShellCompromissoRoute
  '/_shell/cycle-time': typeof ShellCycleTimeRoute
  '/_shell/retrospectivas': typeof ShellRetrospectivasRoute
  '/embed/alocacoes': typeof EmbedAlocacoesRoute
  '/_shell/': typeof ShellIndexRoute
  '/api/public/envprobe': typeof ApiPublicEnvprobeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aceitar-convite'
    | '/admin'
    | '/alocacoes'
    | '/compromisso'
    | '/cycle-time'
    | '/retrospectivas'
    | '/embed/alocacoes'
    | '/api/public/envprobe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/aceitar-convite'
    | '/admin'
    | '/alocacoes'
    | '/compromisso'
    | '/cycle-time'
    | '/retrospectivas'
    | '/embed/alocacoes'
    | '/'
    | '/api/public/envprobe'
  id:
    | '__root__'
    | '/_shell'
    | '/aceitar-convite'
    | '/admin'
    | '/_shell/alocacoes'
    | '/_shell/compromisso'
    | '/_shell/cycle-time'
    | '/_shell/retrospectivas'
    | '/embed/alocacoes'
    | '/_shell/'
    | '/api/public/envprobe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  AceitarConviteRoute: typeof AceitarConviteRoute
  AdminRoute: typeof AdminRoute
  EmbedAlocacoesRoute: typeof EmbedAlocacoesRoute
  ApiPublicEnvprobeRoute: typeof ApiPublicEnvprobeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aceitar-convite': {
      id: '/aceitar-convite'
      path: '/aceitar-convite'
      fullPath: '/aceitar-convite'
      preLoaderRoute: typeof AceitarConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/alocacoes': {
      id: '/_shell/alocacoes'
      path: '/alocacoes'
      fullPath: '/alocacoes'
      preLoaderRoute: typeof ShellAlocacoesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/compromisso': {
      id: '/_shell/compromisso'
      path: '/compromisso'
      fullPath: '/compromisso'
      preLoaderRoute: typeof ShellCompromissoRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/cycle-time': {
      id: '/_shell/cycle-time'
      path: '/cycle-time'
      fullPath: '/cycle-time'
      preLoaderRoute: typeof ShellCycleTimeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/retrospectivas': {
      id: '/_shell/retrospectivas'
      path: '/retrospectivas'
      fullPath: '/retrospectivas'
      preLoaderRoute: typeof ShellRetrospectivasRouteImport
      parentRoute: typeof ShellRoute
    }
    '/embed/alocacoes': {
      id: '/embed/alocacoes'
      path: '/embed/alocacoes'
      fullPath: '/embed/alocacoes'
      preLoaderRoute: typeof EmbedAlocacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/envprobe': {
      id: '/api/public/envprobe'
      path: '/api/public/envprobe'
      fullPath: '/api/public/envprobe'
      preLoaderRoute: typeof ApiPublicEnvprobeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellAlocacoesRoute: typeof ShellAlocacoesRoute
  ShellCompromissoRoute: typeof ShellCompromissoRoute
  ShellCycleTimeRoute: typeof ShellCycleTimeRoute
  ShellRetrospectivasRoute: typeof ShellRetrospectivasRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAlocacoesRoute: ShellAlocacoesRoute,
  ShellCompromissoRoute: ShellCompromissoRoute,
  ShellCycleTimeRoute: ShellCycleTimeRoute,
  ShellRetrospectivasRoute: ShellRetrospectivasRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  AceitarConviteRoute: AceitarConviteRoute,
  AdminRoute: AdminRoute,
  EmbedAlocacoesRoute: EmbedAlocacoesRoute,
  ApiPublicEnvprobeRoute: ApiPublicEnvprobeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
